[package]
name = "ed25519"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name         = "ed25519"
crate-type   = ["rlib", "cdylib"]

[dependencies]
libc = "0.2.106"
ed25519-dalek = "1.0.1"
